### ISSUE TITLE
Recréation des Databases nécessaires

### ISSUE THREAD

**Issue by Scriptodude** [AESSUQAM/EnceFAL#11]
Depuis la version 1.7 de django, south n'est plus supporté (c'était utilisé pour les schéma de tables)

Il faut donc se retapper le travail de reconstruire manuellement les tables de la base de donnée...
On a donc quelques options :

1- garder SQLite3 et refaire manuellement le projet en entier (en important les sources encore compilables) -> Il va falloir utiliser django-admin pour startapp et startproject, ainsi que reconfigurer tout le projet.
2- Recompiler le projet d'origine pour importer la base de donnée déjà construite (bootstrap.py est outdaté et ne fonctionne plus, il faut donc trouver un workaround pour build le projet). La mise à niveau de south vers django 1.9.6 est assez simple.
3- Changer de manager de base de donnée et reconstruire les bases à la main en s'assurant que les sources ont accès à cette base (ça j'ai pas vérifié)

Le plus simple serait l'option 2,  cependant comme mentionné, bootstrap ne fonctionne pas.

**Comment by ventilooo** [comment]
Vous vous y connaissez mieux que moi !
@nilovna @louib

**Comment by Scriptodude** [comment]
Résolu !
J'ai installé les requis manuellement, build up le projet, et remake en django 1.9.6.
D'autres problèmes sont apparus, mais le plus gros est parti ^_^

**Comment by ventilooo** [comment]
La migration de la DB qui est actuellement en production va être compliquer ?

**Comment by Scriptodude** [comment]
En gros, la nouvelle version de Django supporte plus South (pour bâtir les tables de la DB), donc pour mettre à niveau vers django 1.9.6 il faut que le projet soit déjà build et ensuite suivre quelques directives (ce que j'ai fait avec succès).
Maintenant le serveur lance comme sur des roulettes, mais avec quelques erreurs (mise en forme par exemple).

**Comment by ventilooo** [comment]
Ok perfect ! N'oublie pas de splitter tes PR par issue résolue et d'ajouter des test unitaire quand c'est possible.
