### ISSUE TITLE
Rendre la mise en forme du site compatible

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/EnceFAL#14]
Bootstrap.py is no longer used so the general display need to be fix with Something else.
That's an opportunity to integrate #8

**Comment by Scriptodude** [comment]
I think i've found some info on this issue :

## First Information

Firstly, the initial project didn't have manage.py (created by django-admin-tools when starting a new project), that manage.py was suppose to point on the current working directory to help out find files on the server.
- I will try to generate that manage.py and will come back on my progress.

## Second Information

I found out that django integrated a new way of finding static files (before it was MEDIA_*). 
- It now uses STATIC_\* for static files and MEDIA_\* for other files. 
- I will try to change that in settings and see what happens.

**Comment by ventilooo** [comment]
Fix by #18
