### ISSUE TITLE
Integrate Coveroll

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/EnceFAL#17]

**Comment by Scriptodude** [comment]
Salut !

J'ai pas moyen de tester l'intégration de coveralls dans le projet (et j'ai pas envie de me créer un coverall ^_^).
Si tu vas voir dans mon repo, j'ai modifié le .travis.yml pour include coveralls, penses-tu être en mesure de tester ? 

Merci !

**Comment by ventilooo** [comment]
Fait une PR, ça devrais marcher ! Le repo est déjà connecter avec coverolls.

**Comment by ventilooo** [comment]
Done by #21
