### ISSUE TITLE
Test Coverage django

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/EnceFAL#31]
Il semble que coveroll analyse le code de django (lors du JOB sur travic) en plus de celui du projet.

**To fix :** N'avoir que le code du projet qui soit analyser par coveroll

**Comment by Scriptodude** [comment]
Je crois pas qu'on peut ignorer l'exécution du code django.
Je vais essayer de faire le build de .travis.yml sans virtualenv, peut-être que ça va fonctionner.
