### ISSUE TITLE
Enlever les tests.py

### ISSUE THREAD

**Issue by Scriptodude** [AESSUQAM/EnceFAL#38]
Plus précisément, lors du PR #35, j'ai omis de staged les suppression de fichiers suivant : 
- le fichier django/main/tests.py, il est maintenant situé dans django/main/tests/test_*.py
- le fichier django/employee/tests.py, il est maintenant situé dans django/employee/tests/test_*.py

La suppression de ces fichiers devrait augmenter le coveralls encore un peu. :+1:

**Comment by Scriptodude** [comment]
ping @ventilooo Effectuable directement sur le site de github ^.^

**Comment by ventilooo** [comment]
done !
