### ISSUE TITLE
update the .travis.yml for 1.9.6 django

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/EnceFAL#4]
Dans le but d'éviter la casse avec les PR, il faut vérifier les builds et si les test unitaire marche.

**Comment by ventilooo** [comment]
@Scriptodude Ping ?

**Comment by Scriptodude** [comment]
J'y travaille live !
Ça avance assez rapido ^_^

**Comment by ventilooo** [comment]
closed by #13
