### ISSUE TITLE
Taxes (TVQ/TPS)

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/EnceFAL#6]
Implémenter les taxes TPS TVQ mais il doit s'agir d'une option désactivable.

**Comment by Scriptodude** [comment]
Quelques questions :

### Template factures.html
- Est-ce qu'on affiche les numéros gouvernementales de TPS et TVQ dans le template de factures (Si applicable, si existant) ?
- Est-ce qu'on affiche les montant de la TPS et de la TVQ dans le template de factures (Si applicable, si existant) ?

### Template rapport.html
- Dans le template rapport.html, au niveau du prix total, est-ce le prix avec (si applicable) ou sans taxes (dans tous les cas) ?

### Tous les templates en général
- Dans tous les templates où il y a présence de "prix" ou "prix total", est-ce qu'on ajoute une colonne "taxe" avant le prix total, et donc on met à jour le prix total en fonction des taxes ?

### Dans la DB et le code
- L'implémentation optionnelle des taxes vient-elle ajouter des colonnes dans la DB "TPS" et "TVQ"?
- Est-ce que cet ajout de facture vient apporter le besoin d'implémenter une méthode "prix_avant_taxes" et "prix_total" (avec taxes) ?

sur ce, 
je crois avoir fait le tour de mes questionnements,
Cordialement,
Jonathan Lavigne, A.K.A Scriptodude.

**Comment by ventilooo** [comment]
Je vais clarifier la chose.
- Historiquement, il n'y as pas taxes car nous ne dégageons pas de profits sur les vente de livre usagé.

**Cependant**, nous visons à rendre la plateforme ouverte à tous donc il faut que les  utilisateur puisse choisir si il veulent avoir les taxes.
- Dans un tels cas, l'option taxe est activé lors mis en production  initiale de la plateforme.
- Les rapports, DB, templates,etc ... sont modifier pour comporter les taxes avec les numéros gouvernementaux (TPS/TVQ).
  - L'ajout d'une méthode avant taxe et prix total aussi.

@Scriptodude pose moi autant de question que nécessaire (^_^)

**Comment by Scriptodude** [comment]
Bonsoir !

J'ai commencé à penser à l'intégration des taxes et j'ai eu quelques idées que j'ai notés important de te partager (pour avoir ton avis ^_^)
1. La configuration des taxes se ferait sur une page "taxes" et aurait un check box "activer les taxes" et deux barres de textes pour entrer les numéros de TPS et TVQ.
2. La création des factures et des livres se ferait alors normalement. La TPS et la TVQ alors calculé selon le montant total de la facture (comme dans n'importe quel magasin !).
3. Lors de la création d'une facture (sur la page des factures), le numéro de TPS - TVQ serait affiché, le montant des taxes, et le coût total.
4. Si par exemple l'admin décide qu'il veut désactiver les taxes, alors toutes les factures créés seraient supprimé avec un message au vendeur mentionnant la suppression des taxes (Ici je suis pas sûr de mon idée, mais je crois être la façon la plus "safe" pour éviter qu'une facture soit taxée, l'autre non-taxée)

Enfin, j'aimerais ton avis sur le module ^_^!
