### ISSUE TITLE
Calcul d'arrondissement de monnaie

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/EnceFAL#7]

**Comment by Scriptodude** [comment]
Par arrondissement de monnaie tu veux dire :

#### Comme le gouvernement ?
- 5.91 - 5.92$ => 5.90$ 
- 5.93 - 5.94$ => 5.95$
- 5.96 - 5.97$ => 5.95$
- 5.98 - 5.99$ => 6.00$

#### P'tit hack à l'interne ?
- 5.91-5.94 => 5.90$
- 5.95-5.99 => 6.00$

**Comment by ventilooo** [comment]
Comme le Gouvernement !

**Comment by Scriptodude** [comment]
Le site actuel prend en charge seulement les prix entier. Donc pas besoin d'arrondissement de monnaie à moins que l'on change le tout pour prendre en charge les nombre décimaux.

**Comment by ventilooo** [comment]
Done
