### ISSUE TITLE
Intégration de Sématic UI

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/EnceFAL#8]
http://semantic-ui.com/

**Comment by Scriptodude** [comment]
Deux points :
1. Sémantic-UI fait exactement le même travaille que bootstrap (bootstrap-toolkit dans le projet actuel), il y aurait donc confusion et incompatibilité. Si cependant on veut intégrer vers semantic-UI, alors il faut refaire le site web à partir de 0.
2. Quelques recherches ont mené à une découverte que le support de Semantic-UI dans Django assez béta et de base (aucun backup en cas d'erreur, pas de debug, etc.). C'est en fait un projet Git (https://github.com/dpitkevics/Django-Semantic-UI-Forms) qui semble abandonné depuis 9 mois. (stuck à la version 0.1.5)

**Comment by ventilooo** [comment]
Le repo que tu as trouver est juste celui d'une feature. 
- Voici l'original: https://github.com/semantic-org/semantic-ui/
- Voici un projet django qui l'utilise à titre d'exemple: https://github.com/savoirfairelinux/santropol-Der

**Comment by Scriptodude** [comment]
Le deuxième lien est mort.

Mais comme mentionné, semantic-UI est incompatible avec Bootstrap. C'est un ou l'autre, pas les deux en même temps ^_^.

**Comment by ventilooo** [comment]
https://github.com/savoirfairelinux/santropol-feast

**Comment by Scriptodude** [comment]
Je me réexplique :+1: 

Si on intègre sémantic UI, on doit abandonner Boostrap (déjà installé, utilisé dans certaines pages avec des tag django {% TAG %}), c'est-à-dire refaire le site à partir de zéro.

À mon avis on est gagnant à garder Boostrap pour l'instant et intégrer les nouvelles fonctionnalités :100:

**Comment by Scriptodude** [comment]
@ventilooo 

Donc on refait la mise en forme du site, mais basée sur sémantic plutôt que bootstrap ?
De toute façon, il va falloir que je refasse le site admin pratiquement en entier, pourquoi pas pimper un peu l'interface :+1:

**Comment by ventilooo** [comment]
done !
